### ISSUE TITLE
RFE: command/option to toggle off for a user, with permission restriction

### ISSUE THREAD

**Issue by mturley** [trevorzucker/NameHide#3]
Hey @trevorzucker, awesome work here! I had been looking for a proper name hiding plugin that didn't mess with the game's sneak behavior, and this is a brilliant implementation. We're trying it out on a server I'm helping with and noticed a couple small issues (this and #4). I plan to fork it and try my hand at fixing it myself, but I thought you'd want it documented here anyway.

Our moderators like to use the [`/vanish` command provided by CMI](https://www.spigotmc.org/resources/cmi-270-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/) along with creative mode and flying, to patrol and catch cheaters without being detected. The /vanish command just simulates the vanilla behavior of an infinite potion of invisibility (is my understanding). With NameHide enabled, the armor stand name stays on when the player becomes invisible.

**Comment by mturley** [comment]
I'm learning that the CMI vanish isn't actually a vanilla minecraft invis potion mechanic, so the plugin probably can't detect it that way. A fine workaround for this would be just having the ability to toggle these names off, and have a permission setting to allow certain players to do that.

**Comment by mturley** [comment]
Changing this to an RFE for a simple toggle setting, since that won't require integrating with CMI.

**Comment by mturley** [comment]
Planning to try and implement this week and send you a PR!

**Comment by trevorzucker** [comment]
Hey there, sorry for just getting to this!
So, vanishing via an invisibility potion effect is actually able to be detected from Bukkit. I have added two lines of code that will prevent ArmorStands from being created if the visible player has the invisibility. See [version 1.4](https://github.com/trevorzucker/NameHide/releases/tag/1.4)
Thanks for finding this issue!

**Comment by mturley** [comment]
Nice!! Thanks @trevorzucker. I wonder if CMI's /vanish does use that effect after all, time to test it.

**Comment by mturley** [comment]
Looks like it doesn't, but this is a perfect workaround for us for now since we can just make invis potions in creative mode when doing moderator stuff. I still plan to look into a user-level toggle command

**Comment by mturley** [comment]
Hmm, that v1.4 tag/release looks like it's on a commit that updates to 1.3, I don't see the invis potion changes in the source there. Looks like your github tags are one commit ahead? (the 1.3 tag's commit updates to 1.2 also)

**Comment by trevorzucker** [comment]
@mturley I fixed release to reflect that commit. Sorry about that, still learning how to use git. If you can find me the source of the plugin you are referring to, I may be able to get it to hook into the invisibility.

**Comment by mturley** [comment]
Dude no worries at all! I'm the one bothering you on your repo. Nice work with this thing.

I don't think CMI is open source, but they have API docs here: https://www.zrips.net/cmi/api/

**Comment by mturley** [comment]
Btw, if you ever need any help with git or github feel free to reach out. I like teaching :) You can DM me on twitter @mundanedetail
