### ISSUE TITLE
Player nicknames (/nick, via e.g. CMI or Essentials) are not used

### ISSUE THREAD

**Issue by mturley** [trevorzucker/NameHide#4]
Not sure how practical this one is to fix, but it looks like the armor stand nameplate always shows the player's username, even if they have set a different nickname via a /nick command provided by another plugin.

Again, I plan to fork it and try my hand at fixing these myself (this and #3), but I thought you'd want it documented here anyway. Thanks again for your awesome work.

**Comment by trevorzucker** [comment]
Added your fix to the master branch. Thanks for the contribution!
