### ISSUE TITLE
Name tag still shows for a few minutes after player logs out

### ISSUE THREAD

**Issue by mturley** [trevorzucker/NameHide#6]
I noticed that if I log out, my name still appears over where I was standing for a little while.

**Comment by trevorzucker** [comment]
Does this occur on the same client that you log out from?

**Comment by mturley** [comment]
No, when I log back in it corrects itself (I think). But after I log out, my friends who are still in the server can see my name where I was standing.

**Comment by trevorzucker** [comment]
This has been fixed.
